faslib:
  only:
#    - master
#    - devel
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DPARANOID_WARNING=ON ..
    - cmake --build .
    - ctest --output-on-failure
    - cd ..
    - ./.ci/cppcheck.sh
