variables:
  RELEASE_BRANCH: 'release-0.7'
  PROJECT_SSH: "git@github.lan:${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
  REMOTE_SSH:  "git@github.com:migashko/${CI_PROJECT_NAME}.git"

stages:
  - build
  - check
  - merge
  - push

base-build:
  stage: build
  script:
    - ./.ci/build-and-test.sh g++ 98 Release
    - ./.ci/build-and-test.sh g++ 11 Release
  except:
    - /^draft.*$/

full-build:
  stage: build
  script:
    - ./.ci/build-and-test.sh clang++ 98 Release
    - ./.ci/build-and-test.sh clang++ 11 Release
    - ./.ci/build-and-test.sh g++ 14 Release
    - ./.ci/build-and-test.sh clang++ 14 Release
    - ./.ci/build-and-test.sh g++ 98 Debug
    - ./.ci/build-and-test.sh g++ 11 Debug
    - ./.ci/build-and-test.sh g++ 14 Debug
    - ./.ci/build-and-test.sh clang++ 98 Debug
    - ./.ci/build-and-test.sh clang++ 11 Debug
    - ./.ci/build-and-test.sh clang++ 14 Debug
  only:
    - master
    - tags
    - /^build.*$/
  
check-faslib:
  stage: check
  script:
    - ./.ci/cppcheck.sh --std=c++03
    - ./.ci/cppcheck.sh --std=c++11
    - ./.ci/cppcheck.sh --std=c++14
  only:
    - master
    - tags
    - /^check.*$/

tagged-push:
  stage: merge
  script:
    - echo git push ${PROJECT_SSH} ${CI_COMMIT_REF_NAME}:${RELEASE_BRANCH}
    - git push ${PROJECT_SSH} ${CI_COMMIT_REF_NAME}:${RELEASE_BRANCH}
  only:
    - tags

master-merge:
  stage: merge
  script:
    - if [ "${RELEASE_BRANCH}" != "${CI_COMMIT_REF_NAME}" ]; then exit 1; fi
    - ./.ci/headtag.sh ${CI_COMMIT_REF_NAME}
    - HOST=${CI_PROJECT_URL}  CI_PROJECT_ID=${CI_PROJECT_ID} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} ./.ci/automr.sh
  only:
    - /^release.*$/

delete-branch:
  stage: merge
  script:
    - echo git push ${PROJECT_SSH} :${CI_COMMIT_REF_NAME}
    - git push ${PROJECT_SSH} :${CI_COMMIT_REF_NAME}
  only:
    - /^check.*$/
    - /^build.*$/

faslib-push:
  stage: push
  only:
    - master
  script:
    - echo git push ${REMOTE_SSH} master:mambaru
    - git push ${REMOTE_SSH} master:mambaru
    - git push --tags ${REMOTE_SSH} master:mambaru
    