dist:     trusty
sudo:     required

language: cpp

os:
    - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y valgrind

compiler:
    - g++
    - clang++ 
    - g++-5
    - g++-6

env:
    - BUILD_TYPE=Debug STANDARD=98
    - BUILD_TYPE=Release STANDARD=98
    - BUILD_TYPE=Debug STANDARD=11
    - BUILD_TYPE=Release STANDARD=11
    - BUILD_TYPE=Debug STANDARD=14
    - BUILD_TYPE=Release STANDARD=14

matrix:
  exclude:
  - compiler: g++
    env: 
        - BUILD_TYPE=Debug STANDARD=14
        - BUILD_TYPE=Release STANDARD=14
  include:
  - compiler: g++-6
    env: 
       - BUILD_TYPE=Debug STANDARD=17
       - BUILD_TYPE=Release STANDARD=17
  
script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=ON -DPARANOID_WARNING=ON 
      -DCMAKE_CXX_STANDARD=$STANDARD
    - cmake --build .
    - ctest --output-on-failure
